package it.teilibrary.entity;
// Generated 9-set-2016 11.00.18 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ManuscriptTranscriptionId generated by hbm2java
 */
@SuppressWarnings("serial")
@Embeddable
public class ManuscriptTranscriptionId  implements java.io.Serializable {


     private String userUsername;
     private int userRoleIdrole;
     private int manuscriptScanIdmanuscriptScan;

    public ManuscriptTranscriptionId() {
    }

    public ManuscriptTranscriptionId(String userUsername, int userRoleIdrole, int manuscriptScanIdmanuscriptScan) {
       this.userUsername = userUsername;
       this.userRoleIdrole = userRoleIdrole;
       this.manuscriptScanIdmanuscriptScan = manuscriptScanIdmanuscriptScan;
    }
   


    @Column(name="user_username", nullable=false, length=16)
    public String getUserUsername() {
        return this.userUsername;
    }
    
    public void setUserUsername(String userUsername) {
        this.userUsername = userUsername;
    }


    @Column(name="user_role_idrole", nullable=false)
    public int getUserRoleIdrole() {
        return this.userRoleIdrole;
    }
    
    public void setUserRoleIdrole(int userRoleIdrole) {
        this.userRoleIdrole = userRoleIdrole;
    }


    @Column(name="manuscript_scan_idmanuscript_scan", nullable=false)
    public int getManuscriptScanIdmanuscriptScan() {
        return this.manuscriptScanIdmanuscriptScan;
    }
    
    public void setManuscriptScanIdmanuscriptScan(int manuscriptScanIdmanuscriptScan) {
        this.manuscriptScanIdmanuscriptScan = manuscriptScanIdmanuscriptScan;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ManuscriptTranscriptionId) ) return false;
		 ManuscriptTranscriptionId castOther = ( ManuscriptTranscriptionId ) other; 
         
		 return ( (this.getUserUsername()==castOther.getUserUsername()) || ( this.getUserUsername()!=null && castOther.getUserUsername()!=null && this.getUserUsername().equals(castOther.getUserUsername()) ) )
 && (this.getUserRoleIdrole()==castOther.getUserRoleIdrole())
 && (this.getManuscriptScanIdmanuscriptScan()==castOther.getManuscriptScanIdmanuscriptScan());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUserUsername() == null ? 0 : this.getUserUsername().hashCode() );
         result = 37 * result + this.getUserRoleIdrole();
         result = 37 * result + this.getManuscriptScanIdmanuscriptScan();
         return result;
   }   


}


