package it.teilibrary.entity;
// Generated 9-set-2016 11.00.18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Manuscript generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="manuscript"
    ,catalog="mydb"
)
public class Manuscript  implements java.io.Serializable {

	private Integer idmanuscript;
     private String title;
     private String author;
     private Set<ManuscriptScan> manuscriptScans = new HashSet<ManuscriptScan>(0);

    public Manuscript() {
    }

    public Manuscript(String title, String author, Set<ManuscriptScan> manuscriptScans) {
       this.title = title;
       this.author = author;
       this.manuscriptScans = manuscriptScans;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idmanuscript", unique=true, nullable=false)
    public Integer getIdmanuscript() {
        return this.idmanuscript;
    }
    
    public void setIdmanuscript(Integer idmanuscript) {
        this.idmanuscript = idmanuscript;
    }

    
    @Column(name="title", length=45)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="author", length=45)
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="manuscript")
    public Set<ManuscriptScan> getManuscriptScans() {
        return this.manuscriptScans;
    }
    
    public void setManuscriptScans(Set<ManuscriptScan> manuscriptScans) {
        this.manuscriptScans = manuscriptScans;
    }




}


