package it.teilibrary.entity;
// Generated 9-set-2016 11.00.18 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Menu generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="menu"
    ,catalog="mydb"
)
public class Menu  implements java.io.Serializable {


     private MenuId id;
     private Role role;
     private Integer menuda;
     private String menutext;
     private String comando;

    public Menu() {
    }

	
    public Menu(MenuId id, Role role) {
        this.id = id;
        this.role = role;
    }
    public Menu(MenuId id, Role role, Integer menuda, String menutext, String comando) {
       this.id = id;
       this.role = role;
       this.menuda = menuda;
       this.menutext = menutext;
       this.comando = comando;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="menuid", column=@Column(name="menuid", nullable=false) ), 
        @AttributeOverride(name="roleIdrole", column=@Column(name="role_idrole", nullable=false) ) } )
    public MenuId getId() {
        return this.id;
    }
    
    public void setId(MenuId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="role_idrole", nullable=false, insertable=false, updatable=false)
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }

    
    @Column(name="menuda")
    public Integer getMenuda() {
        return this.menuda;
    }
    
    public void setMenuda(Integer menuda) {
        this.menuda = menuda;
    }

    
    @Column(name="menutext", length=20)
    public String getMenutext() {
        return this.menutext;
    }
    
    public void setMenutext(String menutext) {
        this.menutext = menutext;
    }

    
    @Column(name="comando", length=45)
    public String getComando() {
        return this.comando;
    }
    
    public void setComando(String comando) {
        this.comando = comando;
    }




}


