package it.teilibrary.entity;
// Generated 9-set-2016 11.00.18 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MenuId generated by hbm2java
 */
@SuppressWarnings("serial")
@Embeddable
public class MenuId  implements java.io.Serializable {


     private int menuid;
     private int roleIdrole;

    public MenuId() {
    }

    public MenuId(int menuid, int roleIdrole) {
       this.menuid = menuid;
       this.roleIdrole = roleIdrole;
    }
   


    @Column(name="menuid", nullable=false)
    public int getMenuid() {
        return this.menuid;
    }
    
    public void setMenuid(int menuid) {
        this.menuid = menuid;
    }


    @Column(name="role_idrole", nullable=false)
    public int getRoleIdrole() {
        return this.roleIdrole;
    }
    
    public void setRoleIdrole(int roleIdrole) {
        this.roleIdrole = roleIdrole;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MenuId) ) return false;
		 MenuId castOther = ( MenuId ) other; 
         
		 return (this.getMenuid()==castOther.getMenuid())
 && (this.getRoleIdrole()==castOther.getRoleIdrole());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getMenuid();
         result = 37 * result + this.getRoleIdrole();
         return result;
   }   


}


