package it.teilibrary.entity;
// Generated 9-set-2016 11.00.18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Role generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="role"
    ,catalog="mydb"
)
public class Role  implements java.io.Serializable {


     private Integer idrole;
     private String roleDescription;
     private Boolean administrator;
     private Boolean scan;
     private Boolean scanRevisor;
     private Boolean transcriber;
     private Boolean transcriberRevisor;
     private Boolean baseUser;
     private Boolean advancedUser;
     private Set<Menu> menus = new HashSet<Menu>(0);
     private Set<User> users = new HashSet<User>(0);

    public Role() {
    }

    public Role(String roleDescription, Boolean administrator, Boolean scan, Boolean scanRevisor, Boolean transcriber, Boolean transcriberRevisor, Boolean baseUser, Boolean advancedUser, Set<Menu> menus, Set<User> users) {
       this.roleDescription = roleDescription;
       this.administrator = administrator;
       this.scan = scan;
       this.scanRevisor = scanRevisor;
       this.transcriber = transcriber;
       this.transcriberRevisor = transcriberRevisor;
       this.baseUser = baseUser;
       this.advancedUser = advancedUser;
       this.menus = menus;
       this.users = users;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idrole", unique=true, nullable=false)
    public Integer getIdrole() {
        return this.idrole;
    }
    
    public void setIdrole(Integer idrole) {
        this.idrole = idrole;
    }

    
    @Column(name="role_description", length=45)
    public String getRoleDescription() {
        return this.roleDescription;
    }
    
    public void setRoleDescription(String roleDescription) {
        this.roleDescription = roleDescription;
    }

    
    @Column(name="administrator")
    public Boolean getAdministrator() {
        return this.administrator;
    }
    
    public void setAdministrator(Boolean administrator) {
        this.administrator = administrator;
    }

    
    @Column(name="scan")
    public Boolean getScan() {
        return this.scan;
    }
    
    public void setScan(Boolean scan) {
        this.scan = scan;
    }

    
    @Column(name="scan_revisor")
    public Boolean getScanRevisor() {
        return this.scanRevisor;
    }
    
    public void setScanRevisor(Boolean scanRevisor) {
        this.scanRevisor = scanRevisor;
    }

    
    @Column(name="transcriber")
    public Boolean getTranscriber() {
        return this.transcriber;
    }
    
    public void setTranscriber(Boolean transcriber) {
        this.transcriber = transcriber;
    }

    
    @Column(name="transcriber_revisor")
    public Boolean getTranscriberRevisor() {
        return this.transcriberRevisor;
    }
    
    public void setTranscriberRevisor(Boolean transcriberRevisor) {
        this.transcriberRevisor = transcriberRevisor;
    }

    
    @Column(name="base_user")
    public Boolean getBaseUser() {
        return this.baseUser;
    }
    
    public void setBaseUser(Boolean baseUser) {
        this.baseUser = baseUser;
    }

    
    @Column(name="advanced_user")
    public Boolean getAdvancedUser() {
        return this.advancedUser;
    }
    
    public void setAdvancedUser(Boolean advancedUser) {
        this.advancedUser = advancedUser;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="role")
    public Set<Menu> getMenus() {
        return this.menus;
    }
    
    public void setMenus(Set<Menu> menus) {
        this.menus = menus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="role")
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }




}


