package it.teilibrary.entity;
// Generated 9-set-2016 11.00.18 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserId generated by hbm2java
 */
@SuppressWarnings("serial")
@Embeddable
public class UserId implements java.io.Serializable {

    private String username;
    private int roleIdrole;

    public UserId() {
    }

    public UserId(String username, int roleIdrole) {
        this.username = username;
        this.roleIdrole = roleIdrole;
    }

    @Column(name = "username", nullable = false, length = 16)
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @Column(name = "role_idrole", nullable = false)
    public int getRoleIdrole() {
        return this.roleIdrole;
    }

    public void setRoleIdrole(int roleIdrole) {
        this.roleIdrole = roleIdrole;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof UserId)) {
            return false;
        }
        UserId castOther = (UserId) other;

        return ((this.getUsername() == castOther.getUsername()) || (this.getUsername() != null && castOther.getUsername() != null && this.getUsername().equals(castOther.getUsername())))
                && (this.getRoleIdrole() == castOther.getRoleIdrole());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getUsername() == null ? 0 : this.getUsername().hashCode());
        result = 37 * result + this.getRoleIdrole();
        return result;
    }
}
